### ISSUE TITLE
Apply Spring 4 & IO Platform

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/terasoluna-gfw-functionaltest#113]
see terasolunaorg/terasoluna-gfw#132 & terasolunaorg/terasoluna-gfw#178.

- [x] #121 
- [x] Modify pom files. #123 
- [x] Modify to use class of tiles3 (in spring-mvc.xml) #123
- [x] Modify to use dtd of tiles3 (in tiles-definitions.xml) #123
- [x] Add tags-tiles-extras(jsp tag library) in `include.jsp` #123
- [x] Modify as manage scope of libraries by parent project. #123 
- [x] Apply Commons-dbcp2. #123 
- [x] Confirm modification necessity associated with version up of Joda-Time. And  if necessary, please modify.
- [x] Confirm modification necessity associated with spec-change of `@ControllerAdvice`. And  if necessary, please modify.
- [x] Confirm modification necessity associated with version up of Bean Validation. And  if necessary, please modify.
- [x]  Apply namespace of ViewResolver #142
